# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
---
apiVersion: v1
kind: Template
metadata:
  name: hcc-debugger
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: hcc-debugger
    spec:
      feoConfigEnabled: true
      API:
        versions:
          - v1
      envName: ${ENV_NAME}
      title: Starter App
      deploymentRepo: https://github.com/RedHatInsights/hcc-debugger
      frontend:
        paths:
          - /apps/hcc-debugger
      image: ${IMAGE}:${IMAGE_TAG}
      pushCacheEnabled: true

      module:
        manifestLocation: '/apps/hcc-debugger/fed-mods.json'
        modules:
          - id: 'hcc-debugger'
            module: './RootApp'
            routes:
              - pathname: /hcc-debugger

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/hcc-debugger
